### ISSUE TITLE
Point at caspark/ansible-factorio / delete this empty repo?

### ISSUE THREAD

**Issue by caspark** [Kahn/ansible-factorio#1]
Heya, I notice this repo is named the same as my repo over at https://github.com/caspark/ansible-factorio, but it seems like you lost interest/motivation/whatever before pushing anything substantial up.

So in the name of helping out people looking for an easy way to set up factorio: do you think it makes sense to delete this repo or perhaps otherwise point it at caspark/ansible-factorio?

**Comment by Kahn** [comment]
Sure - I had a look at your repo and it looks like you didn't use a galaxy role. I do prefer that all roles are built that way so users can just pick and choose what roles to include via requirements.txt. Are you taking PR's ? :)
